spring.application.name=vantage-search

# Database Connection
spring.datasource.url=jdbc:postgresql://vantage_postgres:5432/vantage_search_db
spring.datasource.username=vantage_user
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Liquibase Configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
